name: Build Polypheny
description: Build a Polypheny JAR
inputs:
  branch:
    description: Polypheny repository ref to checkout
    required: false
    default: 'master'
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: actions/checkout@v4
      with:
        repository: polypheny/Polypheny-DB
        ref: ${{ inputs.branch }}
    - run: ./gradlew build -x test -x licensee
      shell: bash
    - run: ./gradlew build -x test -x licensee
      shell: bash
    - run: 'cd dbms/build/libs/ && mv *.jar polypheny.jar'
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: polypheny-jar
        path: dbms/build/libs/polypheny.jar
